# Everforest themed dark color settings for colorls
#
# Main Colors
unrecognized_file: "#fe8019" # Orange
recognized_file: "#ebdbb2" # Foreground
executable_file: "#b8bb26" # Green
dir: "#b8bb26" # Green

# Link
dead_link: "#fb4934" # Red
link: "#8ec07c" # Cyan

# Special Files
socket: "#b8bb26" # Green
blockdev: "#b8bb26" # Green
chardev: "#b8bb26" # Green

# Access Modes
write: "#d3969b" # Pink
read: "#d3969b" # Purple
exec: "#8ec07c" # Cyan
no_access: "#fb4934" # Red

# Age
hour_old: "#a89984" # Comment - 20% lighter
day_old: "#bdae94" # Comment
no_modifier: "#8ec07c" # Current Line

# File Size
file_large: "#fb4934" # Red
file_medium: "#fabd2f" # Orange
file_small: "#b8bb26" # Green

# Random
report: "#b8bb26" # Green
user: "#8ec07c" # Cyan
tree: "#8ec07c" # Current Line
empty: "#bdae94" # Comment
error: "#fb4934" # Red
normal: "#ebdbb2" # Foreground

# Git
addition: "#8ec07c" # Cyan
modification: "#fabd2f" # Yellow
deletion: "#fb4934" # Red
untracked: "#fe8019" # Orange
unchanged: "#b8bb26" # Green
