
[window]
padding = { x = 8, y = 8 }

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.bold]
family = "Fira Code"
style = "Bold"

[font.bold_italic]
family = "Fira Code"
style = "Bold Italic"

[font.italic]
family = "Fira Code"
style = "Italic"

[font.normal]
family = "Fira Code"
style = "Regular"

[general]
import = [
  "~/.config/alacritty/catppuccin-macchiato.toml"
]
